### ISSUE TITLE
trace2html does not preserve flow events

### ISSUE THREAD

**Issue by yufengshen** [google/trace-viewer#1088] opened 2015-07-07 22:20 UTC
I have a trace file in json format that has flow event
https://drive.google.com/file/d/0B8DyRjJYRslBX0ZXeGNDWGJqekE/view?usp=sharing

after I use trace2html to convert it to html format I can no longer see the flow event.

**Comment by dj2** [comment] 2015-07-08 13:22
Do you have the flow events checkbox checked in the View Options drop down?

**Comment by yufengshen** [comment] 2015-07-08 15:33
Yes, I had it checked and the flow still does not appear.

**Comment by dj2** [comment] 2015-07-08 19:14
The file doesn't show the flow events for me even in the regular viewer. The problem is,  ```event id 0x300000001 does not start at an actual slice, so cannot be created.```

We can't find a start slice so the flow event doesn't get created. This is because we no longer just create flow events but try to associate them to parent slices. This, I think, should get fixed with the new flow event API, but outside that @natduca is there anything we can do to fix this? It looks like it's related to the stuff you were doing to auto link flow events to slices.

**Comment by yufengshen** [comment] 2015-07-08 19:57
So I tested that chrome beta can show the flow event but not the ToT build.
Please advise that how the new flow event API should be used to solve this problem.

The trace is coming from perf bot and currently all the trace from perf bot can't show
the flow event.

**Comment by dj2** [comment] 2015-07-08 20:38
Yea, it's a problem with the code that assumes flow events are associated to a slice. So, it's looking for a parent slice, not finding one, and killing the flow event. Which, I think is a bug. Nat is on vacation at the moment, but hopefully he can look at this when he gets back. I'll bump the priority as this seems like a pretty big issue.

**Comment by natduca** [comment] 2015-07-08 21:51
Yuhao might have ideas.

**Comment by yuhao** [comment] 2015-07-09 01:35
The new Flow Event API will allow us to *explicitly* bind a given flow event with a particular slice. Right now, the trace-viewer uses some heuristics to *guess* which slice a flow event should bind to. When using the heuristics fails to find the bound slice, the flow event won't be created.

We are working on the new API. The design doc is at: https://docs.google.com/document/d/1La_0PPfsTqHJihazYhff96thhjPtvq1KjAUOJu0dvEg/edit#

**Comment by yufengshen** [comment] 2015-07-09 02:04
My question is then does flow event must have a binding slice to show ? I can understand that with binding point you are able to do association, but if I just want to my flow event to show in the trace_viewer and don't care about the association, I can no longer doing that for some format of the
flow event. It forces me to create a binding slice for the flow event now.

**Comment by dj2** [comment] 2015-07-09 12:22
The new API has to support both bound and un-bound flow events.  Unbound events will work like flow events did originally where we just create instant events and link the flows together. Bound events will associate the flow events into slices and link the slices together.

This is case 5 in the document Yuhao linked. Yufeng, does that case cover what you need to do?

**Comment by natduca** [comment] 2015-07-09 15:30
I don't buy that we should support detached flow events. Can someone
explain concisely why it's necessary?

**Comment by yufengshen** [comment] 2015-07-09 15:59
Say I have flow event with category A, and whatever this flow event can bind to DO NOT have category A. I do a trace with only category A enabled, then the flow event has nothing to bind to. Do we want to
support this case ?

**Comment by yufengshen** [comment] 2015-07-09 16:35
Essentially, when I am calling
TRACE_EVENT_FLOW_END_BIND_TO_ENCLOSING("category_a", ...)
there is the risk that the intended enclosing slice does not belong to category_a or there is no
enclosing slice at all.

**Comment by yuhao** [comment] 2015-07-09 17:02
@yufengshen The case you described is exactly what I run into as I am doing the implementation, which is far from finished. I think in that case, we should still create the flow event, but maybe not attach to anything or simply use the existing heuristics to guess where to bind to.

BTW, TRACE_EVENT_FLOW_END_BIND_TO_ENCLOSING is going to be deprecated. In our new APIs, we specify a specific slice to bind to (using some sort of ID), rather than just specifying the enclosing slice.

**Comment by yuhao** [comment] 2015-07-09 17:08
Actually... I took a look at the trace.. The flow event actually does have a binding slice, the problem is the JavaScript floating point issue. Same thing here: #1046

**Comment by yuhao** [comment] 2015-07-09 17:12
The code that tries to find the startSlice of a flow event is at: https://github.com/google/trace-viewer/blob/master/tracing/tracing/extras/importer/trace_event_importer.html#L1139 That ```findSliceAtTs``` function is the one that runs into the JS imprecision issue.

**Comment by natduca** [comment] 2015-07-09 20:53
My request is that whenever the trace model contains a flow event, it is guaranteed to have an start and end event.

That is, we want the model to be fully connected.

This is because the analysis code that we want to build here is very important to our future plans in this space. Having to check every possible flow event to see if its not really a connection between slices but rather just visual decoration adds difficulty for us to pursue this end goal. I would prefer we figure out deeply what the quirks are of input that cause the desire to have non-connected flows, and chase it down to the point that it is fully connected, or we have a crisp a-happens-then-b-then-c-and-c-is-unrelated discussion so we can figure out what makes input flows so special as to skip out on the connectivity graph.

**Comment by randomascii** [comment] 2015-07-09 20:56
I am planning to look at the JS imprecision issue at some point. I could
move up the priority if it is blocking other progress.

I think it's a tractable problem. As long as all timestamps are supposed to
be a multiple of some particular timebase (microseconds or nanoseconds) I
think we just need to round to the nearest multiple of that timebase and
the problem goes away.

On Thu, Jul 9, 2015 at 1:53 PM, Nat Duca <notifications@github.com> wrote:

> My request is that whenever the trace model contains a flow event, it is
> guaranteed to have an start and end event.
>
> That is, we want the model to be fully connected.
>
> This is because the analysis code that we want to build here is very
> important to our future plans in this space. Having to check every possible
> flow event to see if its not really a connection between slices but rather
> just visual decoration adds difficulty for us to pursue this end goal. I
> would prefer we figure out deeply what the quirks are of input that cause
> the desire to have non-connected flows, and chase it down to the point that
> it is fully connected, or we have a crisp
> a-happens-then-b-then-c-and-c-is-unrelated discussion so we can figure out
> what makes input flows so special as to skip out on the connectivity graph.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/trace-viewer/issues/1088#issuecomment-120141241>
> .
>



-- 
Bruce Dawson

**Comment by dj2** [comment] 2015-07-10 12:49
@natduca I don't think we have to make that requirement. We can make the statement that any flow event which is fully connected will be used in our analysis. Any flow event which isn't connect to a slice won't be.

I see no reason to disallow saying, I just want to show an arrow from point a to point b without having it suddenly be part of the rail analysis.

I'm not sure why it adds difficulty to determine if a flow is connected? We could, on import when we determine all the connections set a flow.connected flag. Or, store them in a separate unconnected-flows list which is drawn the old way.

**Comment by natduca** [comment] 2015-07-10 15:05
I'm really sorry Dan, but I still don't support disconnected flow events. You'd be surprised how much code depends on there being child pointers and the flows being followable. If you support disconnected in any way, then it imposes an undue burden on the code. If you insist on us supporting disconnected events, then the only reasonable compromise I can think of is to have an ArrowEvent in the model and make the legacy flow events drive that. But this is, as I said, equally yucky.

**Comment by natduca** [comment] 2015-07-10 15:12
@randomascii that's awesome. Should we have a separate bug for the precision discussion?

**Comment by randomascii** [comment] 2015-07-10 20:59
We already have a separate bug for precision: https://github.com/google/trace-viewer/issues/1046

**Comment by natduca** [comment] 2015-07-27 08:47
@yuhao can we assign this to you to either close/dupe/etc?

**Comment by yuhao** [comment] 2015-08-03 04:01
With the Flow API v2 landed (#1079), this should not be an issue any more since a flow will always have a binding slice when it gets created (or more precisely, there is no "flow events" anymore. there is only a notion of "flow", which is an attribute of a binding slice).

**Closed** 2015-08-04 18:24 UTC
Labels: P1, Trace Viewer
