### ISSUE TITLE
Instant trace events disappear when you zoom in

### ISSUE THREAD

**Issue by natduca** [google/trace-viewer#601] opened 2014-09-22 20:27 UTC
_From [danakj@chromium.org](https://code.google.com/u/danakj@chromium.org/) on August 22, 2014 08:28:05_

Capture a trace with instant events, as you zoom in they disappear entirely.

what labels/people do i add to this?

_Original issue: http://code.google.com/p/trace-viewer/issues/detail?id=596_

**Comment by randomascii** [comment] 2015-03-03 21:42
Also a duplicate of #366

**Comment by dj2** [comment] 2015-03-03 21:44
Closing as a dup of 366.

**Closed by dj2** 2015-03-03 21:44 UTC
Labels: Area-Views, imported, Pri-2, Type-Bug
