### ISSUE TITLE
No tests run and JS errors on console in ui.extras.about_tracing.profiling_view_test

### ISSUE THREAD

**Issue by anniesullie** [google/trace-viewer#1106] opened 2015-07-20 15:19 UTC
When I run the tests, they look finished with 0 failures, but the following happens:

1) RecordSelectionDialog shows in UI after tests finish running
2) ui.extras.about_tracing.profiling_view_test.recording still shows up in state "running"
3) Errors on JavaScript console:
Uncaught (in promise) TypeError: Cannot assign to read only property '0' of ["a","b","c"](…)categories @ record_selection_dialog.html:300showTracingDialog @ record_and_capture_controller.html:105
profiling_view_test.html:62 Uncaught TypeError: Cannot read property 'clickRecordButton' of undefined
4) Cannot press "Record" button in the dialog that shows up, get an "Already recording" exception.

I get the same issue when I click through to http://localhost:8003/base/tests.html?testSuiteName=ui.extras.about_tracing.profiling_view_test

**Comment by anniesullie** [comment] 2015-07-20 16:49
I looked at this a little bit more. It looks like in showTracingDialog(categories), categories was supposed to be an array. But it is a string, coming from "return JSON.stringify(['a', 'b', 'c']);" from proviling_view_test.html. I assume the string was supposed to be JSON.parse() somewhere, but I'm not sure where that was meant to happen.

**Comment by petrcermak** [comment] 2015-07-20 16:58
I'm unable to reproduce the issue. What commit are you on? Have you tried restarting the dev server? Any untracked files in your repository?

**Comment by anniesullie** [comment] 2015-07-20 16:59
I'm synced to 1fbd565e983b74e53a2fa2755137d2a2e9042327, which github tells me is the most recent commit. I will try again from a clean tree in about an hour after some meetings.

**Comment by anniesullie** [comment] 2015-07-20 16:59
(I did try restarting the dev server). It's possible something is wrong with my checkout.

**Comment by petrcermak** [comment] 2015-07-20 17:03
I'm also on 1fbd565 and there are no issues on my machine (I also tried restarting the dev server). I'd suggest checking the output of <tt>git status</tt> if there are any local modifications and/or suspicious untracked files. If that doesn't help, then try making a fresh clone of the repository.

**Comment by anniesullie** [comment] 2015-07-20 17:47
Thanks for taking a look so quickly, @petrcermak! I switched to a different workstation, re-cloned trace-viewer, and opened the tests in chrome stable (Mac 43.0.2357.132) and canary (Mac 46.0.2460.0). I get different results in different Chrome versions. Chrome canary gets the same issue I reported above. Chrome stable fails 3 tests in record_selection_dialog_tests. Git status reports no local modifications or untracked files.

Here are screenshots of the failures:
![screen shot 2015-07-20 at 1 42 41 pm](https://cloud.githubusercontent.com/assets/4331931/8782774/ac86131e-2ee5-11e5-85d3-b0b708f3921f.png)
![screen shot 2015-07-20 at 1 42 41 pm](https://cloud.githubusercontent.com/assets/4331931/8782781/b2af62f4-2ee5-11e5-9324-4ff58bbf5e7c.png)

**Comment by anniesullie** [comment] 2015-07-20 17:49
Apologies, looks like I posted the Canary screen shot twice; here is the Stable one:
![screen shot 2015-07-20 at 1 43 48 pm](https://cloud.githubusercontent.com/assets/4331931/8782854/16f823fe-2ee6-11e5-9820-173fd680b617.png)

**Comment by anniesullie** [comment] 2015-07-20 18:00
Note: I can instantiate the RecordSelectionDialog on stable channel, so I am not blocked by this issue.

**Comment by petrcermak** [comment] 2015-07-20 18:05
This is very strange. I'll have another look at it tomorrow morning.

**Comment by dj2** [comment] 2015-07-20 18:55
Assigning to Charlie for the revert. Please assign to @spang-chromium  once the revert is done.

**Comment by zeptonaut** [comment] 2015-07-20 19:05
My inability to use Github is now recorded for all to see. Sorry for the spam, folks, but should be assigned to the right person now.

**Comment by natduca** [comment] 2015-07-21 02:10
I'm seeing strange errors on ToT too. Not so clear whats going on yet...

I think there's a bug in the test runner where uncaught exceptions aren't causing the test to fail. This is a bug as a result of the d8itification, but the result is that it causes the test runner to hang where it should have failed the test and kept going. Patch incoming.

**Comment by natduca** [comment] 2015-07-21 04:54
This last item, c8dae31 seems to be the core issue that Annie was running into. As she observed, the dialog was receiving a string instead of an array and then trying to mutate it. For some reason that I still don't understand, mutating the string is not permitted in canary, but is permitted in stable. I fixed the issue we were having by passing in an array. I still don't understand why we the string was immutable though... maybe strings become immutable when passed through promises?

**Closed** 2015-08-04 18:25 UTC
