### ISSUE TITLE
Analysis tabs don't interact with back/forward [but should]

### ISSUE THREAD

**Issue by natduca** [google/trace-viewer#706] opened 2015-01-04 23:06 UTC
As you switch between analysis tabs, it doesn't change the selection. This makes sense, except that for us, there is a "global" selection that is managed by timeline_view that is the thing that then is implicitly bound to document.location.

I tried a change to the analysis view to make this work without changing how selection works in trace viewer, but it gets really messy. I think we may need to adopt a routing system.

**Comment by natduca** [comment] 2015-06-09 15:14
@petrcermak ... I kind of thought of the selectioncontroller as persisting state somehow...

**Comment by dj2** [comment] 2015-06-09 15:42
The analysis view used to handle back/forward, is it a function of the tabs that broke it? Do we just need to push state for the tab we're switching too?

**Comment by natduca** [comment] 2015-06-10 03:11
Yeah, its more about the state of the tab --- we don't persist which tab is selected, or any of the state inside the state. The new selection controller has a thing called "brushing state" which is the thing that is supposed to store this info... the main open is figuring out how to allow a sub-view to persist its stuff into the selection controller's brushing state, and have selection controller's current brushing state propagate into the sub views... @petrcermak has ideas though.

**Comment by petrcermak** [comment] 2015-06-18 16:38
I looked at the code and my feeling is that <tt>BrushingState</tt> should contain a dictionary of analysis settings (map from analysis tab type to per-analysis settings object), e.g. <tt>brushingState.analysisSettings['single-memory-dump-analysis-sub-view'] = {...whatever...})</tt>. I think that this model could be extended to other UI components as well.

In the case of analysis settings, there's *no need to push the settings** to the tab. When the user presses back/forward, the current selection changes (this is pushed), which then automatically triggers new construction of all analysis tabs, at which point they can simply query the brushing state.

All we need to do (I think) is to give analysis tabs access to the <tt>BrushingState</tt> object and add two methods <tt>BrushingState.setComponentSettings(componentName, settingsObject)</tt> and <tt>BrushingState.getComponentSettings(componentName)</tt>. This could be later augmented with <tt>BrushingState.setOnComponentSettingsChangedListener(componentName, callback)</tt> for components which do require pushing.

@natduca, @dj2: WDYT?

**Comment by philippebeaudoin** [comment] 2015-06-18 18:37
Fly-by opinion: Petr's proposal SGTM.

**Comment by natduca** [comment] 2015-06-22 20:35
brushingstate having the tab states sounds great.

but, brushing state is supposed to be immutable after construction. lets not change that. its meant to enforce that brushing state changes in one giant move, rather than individual piecewise moves.

thus, you need the selection controller in order to change brushing state.


as far as giving the sub-views access to the controller, i'd love to come up with a way to do this thats not crazy fragile but also not crazy plumbing-heavy...

for instance, it'd be a bummer if we had to plumb a new "selectionController" property from the analysis view down to the subview. that'd mean every subview test that had state would need to be modified, or the subview would be required to function without a selection controller.

i was thinking for a while that we could have a staticmethod SelectionController.getEnclosingControllerForElement(element) that would walk up from the passed in element and find the timeline-view, and then from there find the selection controller. That's what I used in https://codereview.appspot.com/239280043/ in the key event manager.

But, this has the downside that every view that has view-specific-state has to then handle the case where there is no selection controller parent. That would suck for unit tests, in particular.

What I think might be worth considering is the approach that polymer uses here... we make a new element, view-specific-brushing-state that has a set/get/changed event for the view specific state (vss?). The sub-view then instantiates one of these elements and appends it to itself... then the sub-view sends all its vss to this vss element. But, that element doesn't actually hold the state though --- it goes and looks in its parent element hierarchy for the selection controller and pushes/pulls/syncs its state with there. As you point out, we probably don't need to subscribe to change events, but theoretically we could.

Make sense? Thoughts?

Btw lets make sure as part of this work to moves the sunburst state from selection.html to the brushingstate. you'll see a big hack there right now.

**Comment by petrcermak** [comment] 2015-07-03 17:29
I've been thinking about how to incorporate the sunburst state in the view specific brushing state, but I don't see a clean way how to do it. Clearly, we could use the following approach:

  1. User clicks on a node in the sunburst chart to zoom in.
  2. The analysis sub-view persists the selected zoom level (using the new element).
  3. The analysis sub-view fires of the changed selection event.
  4. The analysis view destroys and constructs the sub-view again (due to selection change).
  5. The analysis sub-view retrieves the persisted zoom level (using the new element) and then clears the persisted state (so that it wouldn't affect subsequent selections).
  6. The analysis sub-view can now display the correct node.

However, I don't think that this would be any better than the existing solution, because it would be kind of racy (it relies a lot on the ordering of events) and, more importantly, it would unnecessarily rely on the presence of a selection controller. Moreover, doing this would *not* fix the visual glitch when you click on a node (there's a flicker when you click on a node because the animation doesn't start from the original selection).

In my opinion, it would be better if there was a way for the analysis sub-view to request not to be destroyed when it changes the selection (idea: "I changed the selection and I know how to handle the change myself"). WDYT?

**Comment by natduca** [comment] 2015-07-04 20:07
I like that idea. Making the analysis view not clobber the views would be much more elegant from a basic architecture point of view... if you just want to make it reuse all the views instead of it being opt-in, i'd be supportive.

**Comment by petrcermak** [comment] 2015-07-15 11:18
I wrote a **prototype** of my proposal to **reuse existing previous analysis sub-views** instead of destroying them (see https://codereview.appspot.com/251210043). It's a relatively simple change of <tt>\<tr-ui-a-analysis-view\></tt> that seems to work quite well. Nevertheless, there are two issues:

  1. *Some analysis analysis sub-views rely on being destroyed each time.* For example, <tt>\<tr-ui-a-counter-sample-sub-view\></tt> never clears its children and simply appends new results on each <tt>set selection</tt> call, so it would keep growing until it's destroyed. This would be a regression, but it should be relatively straightforward to fix (by adding something like <tt>this.$.content.textContent = '';</tt> to <tt>set selection</tt>).
  2. *Scroll position of individual tabs is not persisted when selection changes.* It's possible to partially fix this by modifying <tt>\<tr-ui-a-tab-view\></tt> (which is responsible for storing/restoring scroll position on selected tab changes), but this will not work for tabs which contain elements generated asynchronously (especially <tt>\<tr-ui-b-table\></tt>, which is used in almost all  analysis sub-views). It seems that the only way to handle this properly would be to delegate scroll state restoration to the sub-views themselves. Fortunately, this issue would not break any existing behavior (it wouldn't be a bug, but a nice-to-have feature).

What are other people's views on this?

**Comment by dj2** [comment] 2015-07-15 13:17
I think 1 should just be done regardless. Seems like a simple CL.

For 2, I'd skip it. I'm not too concerned at this point if scroll position jumps back to the top. At least it's going back to the right data. I'd file a feature request and skip it.

**Comment by petrcermak** [comment] 2015-07-15 13:31
Sounds good. I think we could do the partial solution for the scroll position straightaway — it's a simple change as well (I updated the patchset with it: https://codereview.appspot.com/251210043/#ps20001)

**Comment by philippebeaudoin** [comment] 2015-07-15 13:32
+1, and we should do (1).

I've actually thought of doing some caching in related_events (I could
imagining situations where computing related events can be expensive) and
it wouldn't be possible unless we kept them around, which needs keeping the
analysis subview around.

**Comment by natduca** [comment] 2015-07-16 02:05
I think @zeptonaut was looking at a rewrite of the counter sample sub view... maybe thats helpful for 1?

Does anyone know the rules for when blink throws away scroll state? I'm not so clear on what we're doing that causes the state to get lost, so its hard for me to form a thought on how to proceed on 2.

**Comment by zeptonaut** [comment] 2015-07-16 14:07
As far as I'm concerned, if something doesn't clear its children when updating contents, it's a bug that should be fixed (I'm certainly willing to help fix these, starting with the counter sample sub view).

**Comment by petrcermak** [comment] 2015-07-16 14:10
Thanks! I went through all Trace Viewer sample files and it seems that **only a few sub-views suffer from this issue**. I'll fix it as part of the patch.

**Comment by petrcermak** [comment] 2015-07-21 10:42
I have created a patch which **removes the sunburst <tt>EventSet</tt> hack** (https://codereview.appspot.com/252350043). It works great (no more visual glitch at the beginning of the transition animation), but there's **still one major issue: history**. When there's an *external* change of the current selection (e.g. when pressing the back button), the sub-view still has no way to determine what the zoom level should be, which leads to the following situation:

![sunburst](https://cloud.githubusercontent.com/assets/2546601/8776524/bb76b122-2ee9-11e5-8f69-a6f9bfc3b198.png)

It turns out that **we still somehow need to remember the zoom level in <tt>BrushingState</tt>**. So we're back to square one: we need to figure out the model for the interaction between analysis tabs and browser history. I have some ideas that I will think more about in the next days.

Regarding the sunburst chart, I don't think it should modify the selection directly. Instead, I think we should extend the concept of <tt>relatedEventsToHighlight</tt> to cater for the case when selection overlaps with highlight (i.e. have something like <tt>SELECTED_AND_HIGHLIGHTED</tt> state or, even better, decouple the two properties).

**Comment by natduca** [comment] 2015-07-21 14:17
Sorry, confused....

When you click on the different tiles, the sunburst chart is pushing view-specific-state to the brushing state controller, right? In theory, each time the vss changes, that should lead to a new brushing state being set on the controller. Whenever that happens, we should be pushStating. Then when you push back, we'd restore an old brushingstate, apply the bs to the analysis view, then the sampling view would boot up and read its vss.

Is there something happening/not-happening in the flow that I'm missing?

**Comment by petrcermak** [comment] 2015-07-21 15:13
In general, you are right. However, there are a couple of things that complicate the flow you described:

  1. When you click on a tile in the sunburst chart, the selection changes (so that the corresponding events would be selected on the timeline view). This complicates things because there is currently no way to change both the selection and the brushing state (zoom level in this case) simultaneously.
  2. Even if there were a way to change both the selection and brushing state simultaneously, we would still run into problems with the history: Consider that the current brushing state is <tt>{selection: S1, zoomLevel: z1}</tt> and the next (or previous) one is <tt>{selection: S2, zoomLevel: z2}</tt>. There is no easy way to determine if the transition should be smooth (i.e. if it was a transition due to a click in the sunburst chart), or not (i.e. if it was a transition due to a proper selection change).
  3. Finally, suppose that you are in a brushing state <tt>{selection: S3, zoomLevel: z3}</tt> and the user initiates a proper change of selection to <tt>S4</tt>. Since (parts of) the brushing states are persistent, we will end up in a brushing state <tt>{selection: S4, zoomLevel: **z3**}</tt> (while we would really want to reset the zoom level and be in <tt>{selection: S4, zoomLevel: **0**}</tt>).

**Comment by natduca** [comment] 2015-07-21 18:14
Re #1, BSC has a set brushingState, right? You can clone the current brushing state, set the selection and the vss, then push that to the BSC as a single setter. Atomic changing of multiple thigns was a key part of the goal of the bsc.... there are those helpers like BSC.setSelection that do the clone and set internally but those are just sugar [maybe we should remove that sugar or explain their role]

**Comment by petrcermak** [comment] 2015-07-24 11:05
Thanks for the reply.

  1. OK, that sounds good.
  2. It is quite difficult to do a smooth transition between two different selections in general (because the sunburst charts can have completely different shapes). I would be a little hesitant to add <tt>lastBrushingState</tt> to <tt>BrushingStateController</tt> because it might add a lot of unnecessary complexity to the whole state logic.
  3. This is true for the overall selection, but the individual analysis sub-views (tabs) get only subsets of it, which are regenerated each time the state changes (so the GUIDs will differ). It would of course be possible to cache the subsets to avoid this.

I think that we should wait until #1117 is resolved, at which point all the issues above become irrelevant (because we don't need to change the overall selection in the sunburst diagram anymore).

**Comment by natduca** [comment] 2015-07-24 16:51
Good counterpoints! I will have a think a bit about this problem space.
Ping me in a week and remind me that this is dangling?

Dumb question: How does link hovering affect sunburst?

**Comment by petrcermak** [comment] 2015-07-27 10:00
I'll make sure we don't forget about this :wink:

Regarding hovering: The reason I referred to #1117 is that adding a "super-highlighted" (i.e. selected+highlighted) state was proposed in the issue. I think that the **"super-highlighted" state** could be used in the sunburst chart instead of changing selection all the time. Here's an example:

   1. User selects the following events: <tt>NotSample</tt> *A*, <tt>Sample</tt> *B*, <tt>Sample</tt> *C*, and <tt>Sample</tt> *D*.

   2. Analysis view is provided with selection *{A, B, C, D}*, which in turn creates (or re-uses) two tabs: "Not Sample (1)" with sub-selection *{A}* and "Samples (3)" with sub-selection  *{B, C, D}*. Suppose that the **non-sample tab is selected** by default (because it's the first tab). The events will consequently have the following states:
     - *A*: selected
     - *B*: selected
     - *C*: selected
     - *D*: selected

   3. User **selects the sample tab**. The sunburst chart in the tab is now showing an overview of *all* the selected samples, so all of them are highlighted in the timeline:
     - *A*: selected
     - *B*: selected+highlighted
     - *C*: selected+highlighted
     - *D*: selected+highlighted

   4. User **clicks on a tile** in the sunburst chart which corresponds to events *B* and *C*. As a result, *D* is not highlighted anymore:
     - *A*: selected
     - *B*: selected+highlighted
     - *C*: selected+highlighted
     - *D*: selected

   4. (optional) User **hovers on a tile** in the sunburst chart which corresponds to event *B*. Consequently, *C* is now temporarily not highlighted either (until the user stops hovering):
     - *A*: selected
     - *B*: selected+highlighted
     - *C*: selected
     - *D*: selected

Note that the selection doesn't change throughout the whole interaction (*{A, B, C, D}* all the time). Instead, the highlight changes depending on the selected tab and its internal state (*∅ → {B, C, D} → {B, C} → {B}*). There are two important **benefits** of this approach that haven't been mentioned so far:

  1. Clicking on a tile in the sunburst chart will __*not* delete other analysis tabs__ (as it is the case now due to selection change).
  2. In addition to zooming in, the user will also be able to freely __zoom out__ (the sunburst chart).

**Comment by natduca** [comment] 2015-07-29 08:06
Ah! I like the idea of sunburst movement just mutating some new brushing state property....

Might mean we should tweak how that all glues up to the brushing controller [right now the analysis view does some mediation which is maybe the wrong call]

But i'm confused if its the same highlighted state that the analysis links mutate, or if we have just lots and lots of different events for the differnet systems and then the bsc merges them together?

**Closed** 2015-08-04 17:25 UTC
Labels: Bug, P1
