### ISSUE TITLE
Error: Implicit snapshots must have names.

### ISSUE THREAD

**Issue by benshayden** [google/trace-viewer#942] opened 2015-05-04 19:13 UTC
Error: Implicit snapshots must have names.
    at Object.processField (chrome://tracing/tracing.js:2654:7)
    at iterObject (chrome://tracing/tracing.js:2663:82)
    at iterObject (chrome://tracing/tracing.js:2671:1)
    at iterObject (chrome://tracing/tracing.js:2666:1)
    at iterObject (chrome://tracing/tracing.js:2671:1)
    at iterObject (chrome://tracing/tracing.js:2666:1)
    at iterObject (chrome://tracing/tracing.js:2671:1)
    at iterObject (chrome://tracing/tracing.js:2666:1)
    at iterObject (chrome://tracing/tracing.js:2671:1)
    at iterObject (chrome://tracing/tracing.js:2666:1)

C.f. https://codereview.chromium.org/1098533002/

trace-viewer git head: 81bdf9c7e78aaf1de66e30edd2f93c05561d6d0f

**Comment by benshayden** [comment] 2015-05-04 19:17
rawId is "messages", so it doesn't appear to be directly related to 1098533002

**Comment by benshayden** [comment] 2015-05-04 19:22
Replacing the throw with a return allows trace viewer to be usable and doesn't seem to have any ill effects.

**Comment by natduca** [comment] 2015-05-05 01:12
can you put up a cl that repros this? or a trace or something so i can see whats being handed to the importer?

**Comment by benshayden** [comment] 2015-05-06 20:41
Emailed you a trace.

**Comment by natduca** [comment] 2015-05-07 19:59
The id field is reserved in the args format. If you use it, it is interpreted to mean "this is a reference to some other object snapshot." So, you need to rename your dumping code in blink to use something other than id as a string.

**Comment by natduca** [comment] 2015-05-22 04:33
Closing, not a bug, confusing error message but no patch. :)

**Closed by natduca** 2015-05-22 04:33 UTC
