### ISSUE TITLE
trace2html not producing valid html

### ISSUE THREAD

**Issue by vmpstr** [google/trace-viewer#876] opened 2015-03-30 22:22 UTC
Hey, not sure if I'm not using this correctly, but running

$ ./trace2html trace.json

with tip of tree chromium trace.json from the root repo, then opening the html gets me this:

Uncaught SyntaxError: Unexpected token ILLEGAL
(this happens on a line that says "/**" without quotes)

And Uncaught SyntaxError: Unexpected token )
(this happens on a valid looking regular expression matching)

Is this a bug or am I not using this correctly?

**Comment by ChrisCraik** [comment] 2015-03-31 00:35
Duplicate of: https://github.com/google/trace-viewer/issues/853

**Closed by ChrisCraik** 2015-03-31 00:35 UTC
