### ISSUE TITLE
Can't record trace in ToT

### ISSUE THREAD

**Issue by natduca** [google/trace-viewer#562] opened 2014-09-22 20:25 UTC
_From [bo...@chromium.org](https://code.google.com/u/110837606391872340358/) on May 21, 2014 09:02:09_

Version: 37.0.2008.0
OS: ChromeOS What steps will reproduce the problem? 1. Open chrome://tracing
2. Click trace button

What is the expected output?
Should see the categories dialog box

What do you see instead?
Sometimes nothing happens. Sometimes I get an error box:
"Error while recording
Error: Error occured at /json/categories at chrome://tracing/tracing.js:5318:31"

It works when I sign out and login with Guest account.

_Original issue: http://code.google.com/p/trace-viewer/issues/detail?id=557_

**Comment by dj2** [comment] 2015-03-03 21:25
Dupe of #538

**Closed by dj2** 2015-03-03 21:25 UTC
Labels: imported, Pri-2, Type-Bug
